name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: "turco-vic"
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualizando a cobrinha 🐍"
          add: "github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg"
          push: true
